# Run with:
# ansible-playbook InstallCertbot.yml

---
- name: Install Certbot
  hosts: all
  tasks:

  - name: Install python3-certbot package on OpenSUSE/SUSE Linux
    zypper:
      name: python3-certbot
      state: present

  - name: Install python3-certbot-apache package on OpenSUSE/SUSE Linux
    zypper:
      name: python3-certbot-apache
      state: present
