# Run with:
# ansible-playbook InstallKernel.yml

---
- name: Install Kernel and Source
  hosts: all
  tasks:

  - name: Install Kernel package on OpenSUSE/SUSE Linux
    zypper:
      name: kernel-default
      state: present

  - name: Install Kernal source extension packages on OpenSUSE/SUSE Linux
    zypper:
      state: present
      name:
        - kernel-default-devel
        - kernel-source

  - name: Check if a reboot is needed on all SUSE/OpenSUSE based servers
    register: linux_reboot_required_file
    stat: path=/boot/do_purge_kernels get_md5=no

  - name: Reboot the SUSE/OpenSUSE box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: linux_reboot_required_file.stat.exists

